name = "List-UtilsBy-XS"
badges = ['github-actions/CI', 'metacpan']
module_maker="ModuleBuild"

[build]
build_class = "builder::MyBuilder"

[no_index]
directory = ['t', 'xt', 'inc', 'share', 'eg', 'examples', 'author', 'benchmark', 'builder']

